version: "3.8"

services:
  neo4j:
    image: neo4j:5
    container_name: neo4j
    ports:
      - 7474:7474    
      - 7687:7687 
    environment:
      - NEO4J_AUTH=neo4j/test1234
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9002:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
        echo 'Waiting for MinIO to be ready...';
        until mc alias set local http://minio:9000 admin password123; do
          sleep 3;
        done;
        echo 'Creating bucket...';
        mc mb local/linkup-media || true;
        echo 'Setting public read-only policy...';
        mc anonymous set download local/linkup-media;
        echo 'Bucket is now publicly readable.';
      "

  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  neo4j_data:
  neo4j_logs:
  minio_data:
  mongodb_data:
